version: "3"
services:
  backend:
    image: node:onbuild
    ports:
      - 8889:8889
      - 9229:9229
    environment:
      - PORT=8889
      - AGENT_USERNAME=james
      - AGENT_PASSWORD=bond
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=realmq
      - DB_USER=postgres
      - DB_PASS=realmq
    volumes:
      - .:/usr/src/app
    links:
      - postgresql:postgresql
    command: npm run debug
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=realmq
      - POSTGRESQL_PASSWORD=realmq
    volumes:
      - ./.db:/bitnami/postgresql
