version: "3"
services:
  backend:
    image: node:onbuild
    ports:
      - 8889:8889
    environment:
      - PORT=8889
      - AGENT_USERNAME=james
      - AGENT_PASSWORD=bond
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=realmq
      - DB_USER=realmq
      - DB_PASS=secret
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - .:/usr/src/app
    links:
      - postgresql:postgresql
    command: npm run start
    extra_hosts:
      - api.realmq.local:${REALMQ_LOCAL_HOST_IP:-0.0.0.0}
      - rtm.realmq.local:${REALMQ_LOCAL_HOST_IP:-0.0.0.0}
  postgresql:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: realmq
      POSTGRES_DB: realmq
    ports:
      - ${HOST_BIND_ADDRESS:-127.0.0.1}:5432:5432
